from datetime import UTC, datetime
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, model_validator


class MRDSDomainModel(BaseModel):
    """Base model for all domain entities with strict validation."""
    model_config = ConfigDict(validate_assignment=True, strict=True, extra="forbid")


class TokenUsage(MRDSDomainModel):
    """Tracks token usage for a single model interaction."""
    prompt_tokens: int = Field(ge=0, description="Number of tokens in the prompt.")
    completion_tokens: int = Field(ge=0, description="Number of tokens in the generated completion.")
    total_tokens: int = Field(ge=0, description="Total tokens used (prompt + completion).")


class LatencyMetrics(MRDSDomainModel):
    """Tracks latency metrics for a model interaction."""
    time_to_first_token_ms: Optional[float] = Field(
        default=None, 
        ge=0.0, 
        description="Latency in milliseconds until the first token is received. None if streaming is not used."
    )
    total_latency_ms: float = Field(ge=0.0, description="Total time in milliseconds taken for the entire request.")


class ModelResponse(MRDSDomainModel):
    """Represents the raw response from an LLM provider."""
    raw_text: str = Field(..., description="The complete text generated by the model.")
    token_usage: TokenUsage = Field(..., description="Token usage statistics for this request.")
    latency: LatencyMetrics = Field(..., description="Latency statistics for this request.")
    finish_reason: Optional[str] = Field(
        default=None, 
        description="The reason the model stopped generating (e.g., 'stop', 'length')."
    )


class PromptConfig(MRDSDomainModel):
    """Configuration defining how to construct and send a prompt to a model."""
    provider: str = Field(..., min_length=1, description="The LLM provider (e.g., 'openai', 'anthropic').")
    model_name: str = Field(..., min_length=1, description="The specific model identifier (e.g., 'gpt-4-turbo').")
    system_prompt: Optional[str] = Field(default=None, description="The system prompt defining model behavior.")
    user_template: str = Field(..., min_length=1, description="The user prompt template. Supports Jinja2 variables.")
    temperature: float = Field(
        default=0.0, 
        ge=0.0, 
        le=2.0, 
        description="Sampling temperature. Default is 0.0 for deterministic evaluation."
    )
    max_tokens: Optional[int] = Field(default=None, gt=0, description="Maximum number of tokens to generate.")


class EvalCase(MRDSDomainModel):
    """A single evaluation test case."""
    id: UUID = Field(default_factory=uuid4, description="Unique identifier for the evaluation case.")
    variables: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Variables to inject into the PromptConfig's user_template."
    )
    expected_output: Optional[str] = Field(
        default=None, 
        description="The exact expected output, if doing exact match evaluation."
    )
    evaluation_criteria: List[str] = Field(
        default_factory=list, 
        description="List of criteria or guidelines for an LLM judge to evaluate this case."
    )


class EvalSuite(MRDSDomainModel):
    """A collection of evaluation cases targeting a specific capability or feature."""
    id: UUID = Field(default_factory=uuid4, description="Unique identifier for the evaluation suite.")
    name: str = Field(..., min_length=1, description="Human-readable name of the evaluation suite.")
    description: Optional[str] = Field(default=None, description="Detailed description of what this suite evaluates.")
    cases: List[EvalCase] = Field(..., min_length=1, description="List of test cases in this suite.")
    default_prompt_config: Optional[PromptConfig] = Field(
        default=None, 
        description="Optional default prompt configuration to use if not overridden."
    )


class RunMetadata(MRDSDomainModel):
    """Metadata detailing the execution context of an evaluation run."""
    run_id: UUID = Field(default_factory=uuid4, description="Unique identifier for the entire evaluation run.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC), 
        description="When the run was initiated."
    )
    triggered_by: str = Field(..., min_length=1, description="The user or CI/CD pipeline that triggered the run.")
    git_commit_hash: Optional[str] = Field(
        default=None, 
        description="The Git commit hash of the code/prompts being evaluated."
    )
    environment: str = Field(..., min_length=1, description="The environment where the run occurred.")


class Score(MRDSDomainModel):
    """A single metric score computed for an evaluation case."""
    metric_name: str = Field(..., min_length=1, description="Name of the metric (e.g., 'faithfulness', 'exact_match').")
    value: float = Field(..., description="The numeric score value.")
    max_value: float = Field(default=1.0, description="The maximum possible value for this metric.")

    @model_validator(mode='after')
    def validate_value_range(self) -> 'Score':
        if self.value > self.max_value:
            raise ValueError(f"Score value ({self.value}) cannot exceed max_value ({self.max_value})")
        return self


class JudgeResult(MRDSDomainModel):
    """Result from an LLM-as-a-judge evaluating a ModelResponse."""
    judge_model_name: str = Field(..., min_length=1, description="The model used to act as the judge.")
    score: float = Field(..., ge=0.0, le=1.0, description="The normalized score assigned by the judge.")
    reasoning: str = Field(..., min_length=1, description="The Chain-of-Thought or explanation provided by the judge.")


class Regression(MRDSDomainModel):
    """Represents a detected regression comparing a current score against a baseline."""
    metric_name: str = Field(..., min_length=1, description="The metric being compared.")
    baseline_score: float = Field(..., description="The score from the baseline run.")
    current_score: float = Field(..., description="The score from the current run.")
    delta: float = Field(..., description="The difference (current_score - baseline_score).")
    is_regression: bool = Field(..., description="True if the delta constitutes a significant regression.")


class EvaluationResult(MRDSDomainModel):
    """The aggregate result of running a single EvalCase."""
    id: UUID = Field(default_factory=uuid4, description="Unique identifier for this specific result.")
    case_id: UUID = Field(..., description="The ID of the EvalCase that was run.")
    run_metadata: RunMetadata = Field(..., description="Metadata of the run this result belongs to.")
    prompt_config: PromptConfig = Field(..., description="The prompt configuration used for this evaluation.")
    response: ModelResponse = Field(..., description="The response generated by the model.")
    scores: List[Score] = Field(default_factory=list, description="All computed metrics/scores for this result.")
    judge_results: List[JudgeResult] = Field(
        default_factory=list, 
        description="Any LLM-as-a-judge evaluations performed."
    )
    regressions: List[Regression] = Field(
        default_factory=list, 
        description="Detected regressions compared to the baseline."
    )
    success: bool = Field(..., description="True if the result passed all assertions and regression checks.")


class RegressionThresholds(MRDSDomainModel):
    """Configuration defining strict bounds for regression detection."""
    max_accuracy_drop: float = Field(default=0.02, description="Maximum allowed accuracy drop (e.g., 0.02 = 2%)")
    max_new_failures: int = Field(default=5, description="Maximum number of new failures allowed")


class RegressionAlert(MRDSDomainModel):
    """An alert generated when a threshold is breached or anomaly detected."""
    alert_type: str = Field(..., description="E.g., 'accuracy_drop', 'high_new_failures', 'statistical_warning'")
    message: str = Field(..., description="Human readable description of the alert")
    severity: str = Field(default="warning", description="Severity level: 'warning', 'critical'")


class RunComparison(MRDSDomainModel):
    """The output object representing the comparison between two runs."""
    baseline_run_id: str = Field(..., description="ID of the baseline run.")
    candidate_run_id: str = Field(..., description="ID of the candidate run.")
    baseline_accuracy: float = Field(..., description="Overall accuracy of the baseline run.")
    candidate_accuracy: float = Field(..., description="Overall accuracy of the candidate run.")
    accuracy_delta: float = Field(..., description="candidate_accuracy - baseline_accuracy")
    new_failures: List[UUID] = Field(..., description="List of case IDs that passed in baseline but failed in candidate.")
    recovered_failures: List[UUID] = Field(..., description="List of case IDs that failed in baseline but passed in candidate.")
    category_deltas: Dict[str, float] = Field(..., description="Accuracy deltas grouped by category/difficulty.")
    alerts: List[RegressionAlert] = Field(default_factory=list, description="List of triggered alerts.")

